name: page
description: Data structure to help paginating (e.g. cursor- or next-token-driven) API calls.
version: 1.3.0
repository: https://github.com/isoos/page
topics:
  - pagination
  - cursor
  - token

environment:
  sdk: '^3.0.0'

dev_dependencies:
  lints: ^4.0.0
  test: ^1.0.0
