name: page
description: Data structure to help paginating (e.g. cursor- or next-token-driven) API calls.
version: 1.2.0
homepage: https://github.com/isoos/page

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.0.0
